name: Compilability check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a", "x86", "x86_64" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Setup the environment
        run: |
          sudo pip3 install meson==1.0.1
          sudo apt-get install nasm ninja-build

      - name: Build docker image
        run: |
          docker build -t ffmpeg_android:6.0 -f tools/docker/Dockerfile .

      - name: Executing the script
        run: |
          docker run -e FAM_ARGS='-all-free -all-gpl -android=21 -abis=${{ matrix.abi }}' -v`pwd`:/mnt/ffmpeg-android-maker ffmpeg_android:6.0

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.abi }}
          path: |
            ${{runner.workspace}}/ffmpeg-android-maker/build/
            ${{runner.workspace}}/ffmpeg-android-maker/output/
          if-no-files-found: error
